// <auto-generated />
using System;
using Amaris.Turnos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amaris.Turnos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TurnosDbContext))]
    [Migration("20260911235257_AddUsuario")]
    partial class AddUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amaris.Turnos.Domain.Entities.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Sucursales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Ciudad = "Bogotá",
                            Direccion = "Cra 13 #60-15",
                            Nombre = "Sucursal Chapinero"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Ciudad = "Medellín",
                            Direccion = "Cl 10 #35-20",
                            Nombre = "Sucursal Poblado"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Ciudad = "Cali",
                            Direccion = "Av 6N #23-45",
                            Nombre = "Sucursal Norte"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Ciudad = "Bucaramanga",
                            Direccion = "Cl 34 #43-15",
                            Nombre = "Sucursal Centro"
                        });
                });

            modelBuilder.Entity("Amaris.Turnos.Domain.Entities.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CedulaCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaHoraActivacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroTurno")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("CedulaCliente", "FechaHoraCreacion");

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("Amaris.Turnos.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreUsuario = "admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEJoP1M+VNn2T9GGi8fB1d/a2wsszc1q1Y258kc4CEpU8K3Y9GOuH9zABt00uTAH6uw=="
                        },
                        new
                        {
                            Id = 2,
                            NombreUsuario = "asesor",
                            PasswordHash = "AQAAAAIAAYagAAAAECZ2l4KsS9ctj9ZlkbxuCUuNxFjgjIsjRmGsQEHWtU9shTE4iTv/0+coeT8+TDe8ig=="
                        });
                });

            modelBuilder.Entity("Amaris.Turnos.Domain.Entities.Turno", b =>
                {
                    b.HasOne("Amaris.Turnos.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Turnos")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Amaris.Turnos.Domain.Entities.Sucursal", b =>
                {
                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
